[package]
name = "whichever-compiles"
description = "Please do not use this."
version = "1.0.0"
authors = ["Mara Bos <m-ou.se@m-ou.se>"]
edition = "2018"
license = "BSD-2-Clause"
repository = "https://github.com/m-ou-se/whichever-compiles"

[lib]
proc_macro = true

[dependencies]
libc = "0.2.88"
